"""Rename position column

Revision ID: 43233d1b5c1d
Revises: 32622f01e09c
Create Date: 2025-09-11 23:29:37.143948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "43233d1b5c1d"
down_revision: Union[str, Sequence[str], None] = "32622f01e09c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hand", sa.Column("player_position", sa.String(), nullable=False))
    op.alter_column("hand", "result", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("hand", "position")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hand", sa.Column("position", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.alter_column("hand", "result", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("hand", "player_position")
    # ### end Alembic commands ###
